export const Users = [
    {
      id:1,
      profilePicture: "assets/person/1.jpeg",
      username: "Shivam pr",
    },
    {
      id:2,
      profilePicture: "assets/person/2.jpeg",
      username: "Vikas pr",
    },
    {
      id:3,
      profilePicture: "assets/person/3.jpeg",
      username: "Vivek pr",
    },
    {
      id:4,
      profilePicture: "assets/person/4.jpeg",
      username: "Subhodip pr",
    },
    {
      id:5,
      profilePicture: "assets/person/5.jpeg",
      username: "Nishant pr",
    },
    {
      id:6,
      profilePicture: "assets/person/6.jpeg",
      username: "Sharad Keshari pr",
    },
    {
      id:7,
      profilePicture: "assets/person/7.jpeg",
      username: "Naveen Kumar",
    },
    {
      id:8,
      profilePicture: "assets/person/8.jpeg",
      username: "Hemant pr",
    },
    {
      id:9,
      profilePicture: "assets/person/9.jpeg",
      username: "Akash pr",
    },
    {
      id:10,
      profilePicture: "assets/person/10.jpeg",
      username: "Sachin pr",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      title: "Title: Hare Krishna",
      desc: 'HG Radhesyam pr is going to come to our Jagannath puri VOICE to bless us with his personal association on 10th of july - declared the posters and the invitation cards sent to the professors , alumunus and the first years .Under the guidance of Hg Raj Gopinath Pr and Hg Sri ram raghav pr the inmates has put immense efforts to bring the standard of our VOICE to the highest possible level for the arrival of his grace Radhesyam pr.the VOICE was thoroughly cleansed , the Notice Board , the preaching report , the prasadam and most importantly all the devotees who have made all these arrangements were eagerly waiting for his arrival . HG Raj Gopinath caught the early bus from tata to ranchi to receive prji personally on airport and not only that throughout the time he stayed and assisted prji setting a personal example how to serve a vaisnava who is senior to us and helping us selflessly by his association.As they reached VOICE, devotees awaiting outside the gate from almost half an hour doing hari naam sankirtan suddenly stopped for a while as if making sure that what their eyes are seeing is actually true - Radhesyam pr is actually here now.SRI HARI NAAM SANKIRTAN KI - JAYY, JAGANNATH PURI VOICE KI - JAYY were the first statements prji said as he entered the gate . As soon as he came - directly all of us proceeded to the temple hall and class for inmates began , prji was sweating as the place was too hot but his face looked so calm and focused in distributing krsna to us . then he saw our preaching report- appreciating our book distribution reports , the no of boys we could reach up to and the no of 1st years who took to chanting the holy names .how great one is, may be seen by how one appreciates even the smallest positive steps that others are trying to take to come closer to lord without comparing or criticizing it . Hg Radhesyam das - a most prominent youth preacher of INDIA who may be giving seminars in hundreds of important cities , addresing a crowd of thousands of people , temple president from about 30 years is so happy and enthusiastic that we could get 30 boys registered for Mayapur visit - it was so amazing to see.He took prasaadam while appreciating our preaching reports (reminding us of one of prabhupada\'s golden instruction - anyone can maintain good health by keeping regular habits and living simply ).and from there he went to professor shailesh\'s accomodation where classes for 1st years and then for professors were scheduled one after another.Like an expert he slashed every single doubt of the 1st years through the audios , videos , ppts and personal experiences . One 1st year named harendra (who is now our VOICE inmate) had prepared two beautiful paintings for prji and prji happily received touching his head to the lotus feet of krishna in both the paintings .Then he moved on for professor preaching while prasaadam serving started for 1st years.Next day morning (11th july) His car reached VOICE at about 4:45 am and the day started with JAPA TALK .we then got to chant together with Hg Radheshyam Pr - he was so focused throughout but afterwards he pointed out - many of us were too loud while chanting . "Our JAPA should be like the humming of bees , we should not disturb other fellows" - he instructed . And then he talked about the power of subconscious mind which make us react almost automatically without much control and how we can refill it with positivity - he stressed on keeping our habits regular (even on that day he was stressing not to extend but to take prasaad on the same time as we take everyday .) After class he gave gifts(sadhu bhusan awards) to each of the devotees for cultivating some particular values at an extraordinary level and inspiring others by their personal example . And then he served prasadam and as he was moving downstairs to proceed to his next journey - he turned back and with a smile told - "Hari Bol " he kept on serving 24 hours , not a single second he could stay without serving Hg Radhesyam Pr Visit Thursday, August 31, 2023 9:24 PMeven while going on the way to MAYAPUR he had to take an online session, in a random hardware shop , he made the car stop - he kept his laptop on a pile of plywoods and sitting on some water jar- he was giving session to some foreign devotees , completely absorbed in his service and totally indifferent to the external environment .',
      photo: "assets/post/1.jpeg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      title: "Title: Hare Krishna",
      photo: "assets/post/2.jpeg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      title: "Title: Hare Krishna",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      // photo: "assets/post/3.jpeg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      title: "Title: Hare Krishna",
      photo: "assets/post/4.jpeg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      title: "Title: Hare Krishna",
      desc: "Being Krishna Conscious is the means and the goal of Human Life",
      photo: "assets/post/5.jpeg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      title: "Title: Hare Krishna",
      photo: "assets/post/6.jpeg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      title: "Title: Hare Krishna",
      desc: "Never regret anything that made you smile.",
      photo: "assets/post/7.jpeg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      title: "Title: Hare Krishna",
      photo: "assets/post/8.jpeg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      title: "Title: Hare Krishna",
      desc: "Change the world by being yourself.",
      photo: "assets/post/9.jpeg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      title: "Title: Hare Krishna",
      photo: "assets/post/10.jpeg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];