export default {
  FETCH_DONORS_LIST_SUCCESS: "FETCH_DONORS_LIST_SUCCESS",
  FETCH_DONORS_LIST_ACTION: "FETCH_DONORS_LIST_ACTION",
  FETCH_DONORS_LIST_FAILURE: "FETCH_DONORS_LIST_FAILURE",
  FETCH_EXPENSES_LIST_ACTION: "FETCH_EXPENSES_LIST_ACTION",
  FETCH_EXPENSES_LIST_SUCCESS: "FETCH_EXPENSES_LIST_SUCCESS",
  DONORS: "donors",
  EXPENSES: "expenses",
};
